name       : libieee1284
version    : 0.2.11
release    : 3
source     :
    - https://github.com/twaugh/libieee1284/archive/V0_2_11.tar.gz : eb6a4305f5d44f74b548c8dd41ec1103175cabb57f9661bec4af49e11f8a0238
license    :
    - GPL-2.0+
    - GFDL-1.1+
component  : system.utils
summary    : ieee1284 parallel port library
description: |
    This library is intended to be used by applications that need to communicate with (or at least identify) devices that are attached via a parallel port.
builddeps  :
    - xmlto
    - docbook-xml
setup      : |
    sh bootstrap
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
